// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blihcvwpigvyjlslvzso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsaWhjdndwaWd2eWpsc2x2enNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDkxNTEsImV4cCI6MjA3MjgyNTE1MX0.b5NeNrcw9oL2BAnkoJBXxGLuHCqrYlT1zuKLfVdDHsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});